## **Part A: Dataset Understanding**

In [2]:
#Q1.Load the dataset and display the first five records.
import pandas as pd
df = pd.read_csv("Dataset 2.csv")
df.head()

,UserID,Age,Gender,SubscriptionType,WatchHoursPerWeek,DevicesUsed,FavoriteGenre,AdClicks,MonthlySpend,SubscriptionRenewed
0,1001,22,Female,Basic,23,5,Comedy,13,353,No
1,1002,55,Male,Basic,9,4,Drama,14,317,Yes
2,1003,49,Male,Basic,8,3,Comedy,16,309,No
3,1004,39,Female,Premium,19,5,Drama,45,833,Yes
4,1005,38,Female,Premium,23,5,Sci-Fi,24,804,Yes

In [8]:
#Q2. Determine the number of rows and columns in the dataset.
print('rows , columns = ', df.shape)

rows , columns =  (750, 10)

In [9]:
# 3 .Display all column names.
df.columns

Index(['UserID', 'Age', 'Gender', 'SubscriptionType', 'WatchHoursPerWeek',
       'DevicesUsed', 'FavoriteGenre', 'AdClicks', 'MonthlySpend',
       'SubscriptionRenewed'],
      dtype='object')

Q4. Identify numerical and categorical features.

Numerical Features

-UserID

- Age

- WatchHoursPerWeek

- DevicesUsed

- AdClicks

- MonthlySpend


Categorical Features

- Gender

- SubscriptionType

- FavoriteGenre

- SubscriptionRenewed

In [10]:
#Q5. Check whether the dataset contains missing values.
df.isnull().sum()

UserID                 0
Age                    0
Gender                 0
SubscriptionType       0
WatchHoursPerWeek      0
DevicesUsed            0
FavoriteGenre          0
AdClicks               0
MonthlySpend           0
SubscriptionRenewed    0
dtype: int64

## **Part B: Exploratory Data Analysis**

In [11]:
#Q6.Calculate the average age of users.
df["Age"].mean()

np.float64(41.824)

In [12]:
#Q7.Determine the average watch hours per week.
df["WatchHoursPerWeek"].mean()

np.float64(14.236)

In [13]:
#Q8.Find the average monthly spending of users.
df["MonthlySpend"].mean()

np.float64(689.9053333333334)

In [14]:
#Q9.Count the number of users in each subscription category.
df["SubscriptionType"].value_counts()

SubscriptionType
Basic      342
Premium    279
VIP        129
Name: count, dtype: int64

In [15]:
#Q10.Determine the percentage of users who renewed their subscriptions.
(df["SubscriptionRenewed"]=="Yes").mean()*100

np.float64(46.266666666666666)

## **Part C: Data Preparation**

In [16]:
#Q11.Convert categorical features into numerical form.
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["Gender"] = le.fit_transform(df["Gender"])
df["SubscriptionType"] = le.fit_transform(df["SubscriptionType"])
df["FavoriteGenre"] = le.fit_transform(df["FavoriteGenre"])
df["SubscriptionRenewed"] = le.fit_transform(df["SubscriptionRenewed"])

In [17]:
#Q12.Define the feature set (X) and target variable (y) for subscription renewal prediction.
X = df.drop("SubscriptionRenewed", axis=1)
y = df["SubscriptionRenewed"]

In [19]:
#Q13.Split the dataset into training and testing sets.
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
X, y,test_size=0.2,random_state=42)

## **Part D: Decision Tree Classification**

In [20]:
#Q14.Train a Decision Tree model to predict whether a user will renew their subscription.
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [21]:
#Q15.Evaluate the model using accuracy.
from sklearn.metrics import accuracy_score
y_pred = dt.predict(X_test)
accuracy_score(y_test, y_pred)

0.5666666666666667

In [22]:
#Q16.Generate and interpret the confusion matrix.
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[50 32]
 [33 35]]

## **Part E: K-Nearest Neighbors (KNN)**

In [23]:
#Q17.Train a KNN classifier with K = 5.
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [24]:
#Q18.Compare the accuracy of KNN with the Decision Tree model.
knn_pred = knn.predict(X_test)
accuracy_score(y_test, knn_pred)

0.6

## **Part F: Linear Regression**

In [25]:
#Q19.Train a Linear Regression model to predict monthly spending.
from sklearn.linear_model import LinearRegression
X_reg = df.drop("MonthlySpend", axis=1)
y_reg = df["MonthlySpend"]
X_train, X_test, y_train, y_test = train_test_split(
X_reg,
y_reg,
test_size=0.2,
random_state=42
)
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [26]:
#Q20.Predict the monthly spending for a new user and interpret the result.
sample_user = X_reg.iloc[[0]]
prediction = lr.predict(sample_user)
print(prediction)

[391.38516281]